[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
yapper_escrow = "7Kzwk5x4WKmQ8U9yc3TRcAsmuLBu1NSiQBaBPK4a5gTi"

[programs.devnet]
yapper_escrow = "7Kzwk5x4WKmQ8U9yc3TRcAsmuLBu1NSiQBaBPK4a5gTi"

[programs.mainnet]
yapper_escrow = "7Kzwk5x4WKmQ8U9yc3TRcAsmuLBu1NSiQBaBPK4a5gTi"

[registry]
url = "https://api.apr.dev"

[provider]
# Switch to "localnet" for local validator, "devnet" for testnet
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
